apiVersion: tutorial.operator/v1
kind: Demo
metadata:
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: demo-sample
    app.kubernetes.io/part-of: demo-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: demo-operator
  name: demo-sample
spec:
  # TODO(user): Add fields here
